// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	articleapi "github.com/quarkcms/quark-micro/cmd/post/api/biz/router/articleapi"
	pageapi "github.com/quarkcms/quark-micro/cmd/post/api/biz/router/pageapi"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	pageapi.Register(r)

	articleapi.Register(r)
}
