// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	handler "github.com/quarkcms/quark-hertz/cmd/api/biz/handler"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/api/admin/:resource/index", handler.ResourceIndex)

	// your code ...
}
