// Code generated by hertz generator.

package navigationapi

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _navigationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcategorylistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getnavigationlistMw() []app.HandlerFunc {
	// your code...
	return nil
}
