// Code generated by Kitex v0.4.4. DO NOT EDIT.

package bannerservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	banner "github.com/quarkcms/quark-micro/cmd/banner/rpc/kitex_gen/banner"
)

func serviceInfo() *kitex.ServiceInfo {
	return bannerServiceServiceInfo
}

var bannerServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "BannerService"
	handlerType := (*banner.BannerService)(nil)
	methods := map[string]kitex.MethodInfo{
		"GetBannerList": kitex.NewMethodInfo(getBannerListHandler, newBannerServiceGetBannerListArgs, newBannerServiceGetBannerListResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "banner",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func getBannerListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*banner.BannerServiceGetBannerListArgs)
	realResult := result.(*banner.BannerServiceGetBannerListResult)
	success, err := handler.(banner.BannerService).GetBannerList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBannerServiceGetBannerListArgs() interface{} {
	return banner.NewBannerServiceGetBannerListArgs()
}

func newBannerServiceGetBannerListResult() interface{} {
	return banner.NewBannerServiceGetBannerListResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetBannerList(ctx context.Context, req *banner.BannerListRequest) (r *banner.BannerListResponse, err error) {
	var _args banner.BannerServiceGetBannerListArgs
	_args.Req = req
	var _result banner.BannerServiceGetBannerListResult
	if err = p.c.Call(ctx, "GetBannerList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
