// Code generated by Kitex v0.4.4. DO NOT EDIT.
package bannerservice

import (
	server "github.com/cloudwego/kitex/server"
	banner "github.com/quarkcms/quark-micro/cmd/banner/rpc/kitex_gen/banner"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler banner.BannerService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
