// Code generated by Kitex v0.4.4. DO NOT EDIT.
package navigationservice

import (
	server "github.com/cloudwego/kitex/server"
	navigation "github.com/quarkcloudio/quark-micro/cmd/navigation/rpc/kitex_gen/navigation"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler navigation.NavigationService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
