// Code generated by Kitex v0.4.4. DO NOT EDIT.

package categoryservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	category "github.com/quarkcms/quark-micro/cmd/category/rpc/kitex_gen/category"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetCategoryDetail(ctx context.Context, req *category.CategoryDetailRequest, callOptions ...callopt.Option) (r *category.CategoryDetailResponse, err error)
	GetCategoryList(ctx context.Context, req *category.CategoryListRequest, callOptions ...callopt.Option) (r *category.CategoryListResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kCategoryServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCategoryServiceClient struct {
	*kClient
}

func (p *kCategoryServiceClient) GetCategoryDetail(ctx context.Context, req *category.CategoryDetailRequest, callOptions ...callopt.Option) (r *category.CategoryDetailResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCategoryDetail(ctx, req)
}

func (p *kCategoryServiceClient) GetCategoryList(ctx context.Context, req *category.CategoryListRequest, callOptions ...callopt.Option) (r *category.CategoryListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCategoryList(ctx, req)
}
