init:
	hz new -mod github.com/quarkcms/quark-micro/cmd/navigation/api -idl ./idl/navigation.thrift

update:
	hz update -mod github.com/quarkcms/quark-micro/cmd/navigation/api -idl ./idl/navigation.thrift