init:
	hz new -mod github.com/quarkcms/quark-micro/cmd/post/api -idl ./idl/article.thrift
	hz new -mod github.com/quarkcms/quark-micro/cmd/post/api -idl ./idl/page.thrift

update:
	hz update -mod github.com/quarkcms/quark-micro/cmd/post/api -idl ./idl/article.thrift
	hz update -mod github.com/quarkcms/quark-micro/cmd/post/api -idl ./idl/page.thrift