// Code generated by Kitex v0.4.4. DO NOT EDIT.
package postservice

import (
	server "github.com/cloudwego/kitex/server"
	post "github.com/quarkcloudio/quark-micro/cmd/content/rpc/kitex_gen/post"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler post.PostService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
