// Code generated by hertz generator.

package Articleapi

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _articleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _get_rticledetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _get_rticlelistMw() []app.HandlerFunc {
	// your code...
	return nil
}
